spring:
  profiles:
    active:
    - dev
---    
spring:
  profiles: dev 
  application:
    name: microservicecloud-config-zzk-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-zzk-test